spring:
  application:
    name: pr-review-server
  
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY}

github:
  app:
    id: ${GITHUB_APP_ID}
    installation-id: ${GITHUB_APP_INSTALLATION_ID}
    private-key-path: ${GITHUB_APP_PRIVATE_KEY_PATH:secrets/review-mate-ai.2026-01-05.private-key.pem}
  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET}
