package greensnaback0229.pr_review_server.github;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.kohsuke.github.GHIssueComment;
import org.kohsuke.github.GHPullRequest;
import org.kohsuke.github.GHRepository;
import org.kohsuke.github.GitHub;
import org.springframework.stereotype.Service;

import java.io.IOException;

/**
 * GitHub PR에 코멘트를 작성하는 서비스
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class GitHubCommentService {
    
    private final GitHub github;
    
    /**
     * PR에 리뷰 결과를 코멘트로 작성
     *
     * @param repoFullName 저장소 풀네임 (예: owner/repo)
     * @param prNumber PR 번호
     * @param reviewContent 리뷰 내용
     * @throws IOException GitHub API 호출 실패 시
     */
    public void postReviewComment(String repoFullName, int prNumber, String reviewContent) throws IOException {
        log.info("Posting review comment to {}/#{}", repoFullName, prNumber);
        
        try {
            GHRepository repository = github.getRepository(repoFullName);
            GHPullRequest pullRequest = repository.getPullRequest(prNumber);
            
            // 코멘트 작성
            String comment = formatReviewComment(reviewContent);
            GHIssueComment postedComment = pullRequest.comment(comment);
            
            log.info("Successfully posted comment #{} to {}/#{}", 
                    postedComment.getId(), repoFullName, prNumber);
            
        } catch (IOException e) {
            log.error("Failed to post comment to {}/{}: {}", 
                    repoFullName, prNumber, e.getMessage(), e);
            throw e;
        }
    }
    
    /**
     * 리뷰 내용을 GitHub 코멘트 형식으로 포맷팅
     *
     * @param reviewContent 원본 리뷰 내용
     * @return 포맷팅된 코멘트
     */
    private String formatReviewComment(String reviewContent) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("## 🤖 AI Code Review\n\n");
        sb.append(reviewContent);
        sb.append("\n\n---\n");
        sb.append("*Generated by PR Review Mate*");
        
        return sb.toString();
    }
}
